### ISSUE TITLE
Do you have any plans to update this to Redwood JS 4.4? 

### ISSUE THREAD

**Issue by KevinSeghetti** [rushabhhere/redwood-tutorial-ts#1]
I am new to Redwoodjs, and would like to finish the tutorial with typescript, but they are up to version 4.4. Do you have any plans to update this?

**Comment by rushabhhere** [comment]
@KevinSeghetti I understand your need, but I don't have any plans to keep updating this repository. I'll archive this repository to avoid any confusion.
